# See: https://google.github.io/googletest/quickstart-bazel.html

cc_test(
    name = "cattest",
    size = "small",
    srcs = ["cattest.cpp"],
    deps = [
        "//catlib",
        "@com_google_googletest//:gtest_main",
    ],
)
